version: '3.8'

services:
  postgres-test:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: messenger_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service-test:
    build: 
      context: ./backend
      target: development
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: test
      DATABASE_URL: postgresql://test_user:test_password@postgres-test:5432/messenger_test
      REDIS_URL: redis://redis-test:6379
      JWT_ACCESS_SECRET: test_access_secret_key_for_testing_min_32_chars
      JWT_REFRESH_SECRET: test_refresh_secret_key_for_testing_min_32_chars
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_EXPIRY: 7d
      GOOGLE_CLIENT_ID: test_google_client_id
      GOOGLE_CLIENT_SECRET: test_google_client_secret
      LOG_LEVEL: error
    command: npm run dev
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
